workspace: true

stages:
- build
- test

jobs:
- name: build:prepare
  stage: build
  image: sunci/ruby:2.7.0
  script:
  - cp database-ci.yml config/database.yml
  - bundle _2.1.2_ install --path vendor/bundle
  cache:
  - key: vendor_$CI_BRANCH
    paths:
    - vendor/bundle

- name: test:rspec
  stage: test
  image: sunci/ruby:2.7.0
  services:
  - image: mysql:5.7.22
    name: mysql_test
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: password_test
      MYSQL_ROOT_PASSWORD: password_test
  before_script:
  - bundle _2.1.2_ install --path vendor/bundle
  - bundle _2.1.2_ exec rake db:drop db:create db:migrate
  - mkdir .sun-ci
  script:
  - gem install rspec_junit_formatter
  - DISABLE_SPRING=1 bundle _2.1.2_ exec rspec --format html --out .sun-ci/rspec.html spec/  --format RspecJunitFormatter --out .sun-ci/coverage/junit.xml
  only:
    branches:
    - master
  artifacts:
    name: rspec_report
    paths:
    - .sun-ci
    expires_in: 3 days

- name: test:rubocop
  stage: test
  image: sunci/ruby:2.7.0
  before_script:
  - bundle _2.1.2_ install --path vendor/bundle
  script:
  - bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color app/ lib/
